# Generated by Django 5.1.1 on 2024-10-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_orders_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
