# Generated by Django 5.1.1 on 2025-10-24 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderproduct_quantity"),
        ("products", "0003_remove_product_photo_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderproduct",
            unique_together={("order", "product")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "is_active"], name="orders_orde_user_id_e9e212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderproduct",
            index=models.Index(
                fields=["order", "product"], name="orders_orde_order_i_b7e52c_idx"
            ),
        ),
    ]
