# Generated by Django 5.1.1 on 2025-10-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderproduct_unique_together_and_more"),
        ("products", "0003_remove_product_photo_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
