# Generated by Django 5.1.1 on 2025-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank="True", null="True", upload_to="", verbose_name="Image"
            ),
            preserve_default="True",
        ),
    ]
