# Generated by Django 5.1.1 on 2025-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_photo_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank="True",
                default="assets/image_not_available.png",
                null="True",
                upload_to="products",
                verbose_name="Image",
            ),
        ),
    ]
